apiVersion: v1
kind: Service
metadata:
  name: echo-api-sidecar
  namespace: hybrid-tenant
spec:
  type: NodePort
  selector:
    app: echo-api-sidecar
  ports:
  - name: http
    port: 80
    targetPort: 8000
    nodePort: 30003
