apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: centralized-tenant
data:
  default.conf: |
    # Extract Token from "Bearer <token>"
    map $http_authorization $user_access_token {
        "~^Bearer (.*)$" $1;
        default "";
    }

    server {
        listen 80;
        resolver 10.96.0.10 valid=5s;

        # Main Entrypoint
        location /echo {
            auth_request /auth;
            
            set $upstream_endpoint http://echo-api.centralized-tenant.svc.cluster.local:80;
            proxy_pass $upstream_endpoint;
        }

        # Internal Authorization Sub-request (UMA)
        location = /auth {
            internal;
            
            set $token_endpoint http://toxiproxy.common-central.svc.cluster.local:8080/realms/demo/protocol/openid-connect/token;
            proxy_pass $token_endpoint;

            # Headers
            proxy_set_header Host toxiproxy.common-central.svc.cluster.local:8080;
            proxy_method POST;
            proxy_set_header Content-Type "application/x-www-form-urlencoded";
            proxy_set_header Authorization "";
            
            # Construct UMA Ticket Request Body
            proxy_set_body "grant_type=urn:ietf:params:oauth:grant-type:uma-ticket&audience=nginx-pep&permission=echo-resource&client_id=nginx-pep&client_secret=secret&subject_token_type=urn:ietf:params:oauth:token-type:access_token&response_mode=decision&subject_token=$user_access_token";
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-pep
  namespace: centralized-tenant
  labels:
    app: nginx-pep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-pep
  template:
    metadata:
      labels:
        app: nginx-pep
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/conf.d
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-conf
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-pep
  namespace: centralized-tenant
spec:
  type: NodePort
  selector:
    app: nginx-pep
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001
